WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F18AD42090>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b15f26ada0fe6f8d214f1119628d498c
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F18AD422A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b15f26ada0fe6f8d214f1119628d498c
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F18AD424E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b15f26ada0fe6f8d214f1119628d498c