WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000218ACCFD250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2b4236f39d733b25b442b4859f1926df
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000218ACCFD730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2b4236f39d733b25b442b4859f1926df
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000218ACCFD8E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2b4236f39d733b25b442b4859f1926df