WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002F0FC67D580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f921f09e0ef5097ad286aad0dc93fc30
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002F0FC67D280>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f921f09e0ef5097ad286aad0dc93fc30
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002F0FC67D820>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f921f09e0ef5097ad286aad0dc93fc30