WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000208A50206B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c46ca98d3de8dae503be4c50cd346b6e
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000208A5020710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c46ca98d3de8dae503be4c50cd346b6e
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000208A50208C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/c46ca98d3de8dae503be4c50cd346b6e